dependencies:
  - role: ansible-role-unattended-upgrades
    when: ansible_os_family == "Debian"
    become: yes
    unattended_automatic_reboot: true
    unattended_remove_unused_dependencies: true
    unattended_mail: "{{ target_user }}"
    unattended_origins_patterns:
      - origin=Debian,codename=${distro_codename}
      - label=Debian-Security
  - apps
  - mosh
  - fish
  - dotfiles
  - autojump
  - gpg
  - asdf
  - aws
  - git
