---
- name: clone systemd-factorio-docker repository
  git:
    repo: https://github.com/shepherdjerred/systemd-factorio-docker
    dest: "/home/{{ target_user }}/git/systemd-factorio-docker"
    update: yes
- name: create data directory
  file:
    path: /server/data
    state: directory
    group: 845
    owner: 845
- name: copy systemd service file
  become: yes
  copy:
    src: "/home/{{ target_user }}/git/systemd-factorio-docker/docker.factorio.service"
    remote_src: yes
    dest: "/etc/systemd/system"
    owner: root
    group: root
- name: enable docker.factorio.service
  become: yes
  systemd:
    name: docker.factorio.service
    state: restarted
    enabled: yes

