dependencies:
  - nas-raid
  - sonarr
  - filebot
  - plex
  - syncthing
  - ufw-syncthing
  - resilio-sync
  - role: jnv.unattended-upgrades
    become: yes
    unattended_automatic_reboot: true
    unattended_remove_unused_dependencies: true
    unattended_mail: "{{ target_user }}"
    unattended_origins_patterns:
      - origin=Debian,codename=${distro_codename}
      - label=Debian-Security
      - site=linux-packages.resilio.com
      - site=downloads.plex.tv
      - site=get.filebot.net
      - site=apt.syncthing.net
  - apache
  - ufw-apache
