---
- name: clone spigot-docker repository
  git:
    update: yes
    repo: https://github.com/shepherdjerred-minecraft/spigot-docker
    dest: "/home/{{ target_user }}/git/spigot-docker"
- name: create data directory
  file:
    path: /server/data
    state: directory
    group: ec2-user
    owner: ec2-user
- name: copy systemd service file
  become: yes
  copy:
    src: "/home/{{ target_user }}/git/spigot-docker/docker.spigot.service"
    remote_src: yes
    dest: "/etc/systemd/system"
    owner: root
    group: root
- name: enable docker.spigot.service
  become: yes
  systemd:
    name: docker.spigot.service
    state: restarted
    enabled: yes
