ansible_python_interpreter: auto_silent
target_user: jerred
bootstrap_user: jerred
ansible_user: "{{ bootstrap_user }}"
ansible_ssh_pass: "{{ master_password }}"
ansible_sudo_pass: "{{ master_password }}"
ansible_become_pass: "{{ master_password }}"
