---
- name: install zsh
  become: yes
  package:
    name: zsh
- name: set zsh as the default shell for root
  become: yes
  user:
    name: root
    shell: /usr/bin/zsh
- name: set zsh as the default shell for "{{ target_user }}"
  become: yes
  user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh
