---
- name: install epel
  become: yes
  shell: yes | amazon-linux-extras install epel
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
- name: install ufw
  become: yes
  package:
    name: ufw
- name: allowlist ssh
  become: yes
  ufw:
    rule: allow
    name: ssh
- name: enable ufw
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming
