---
- name: install mosh
  become: yes
  package:
    update_cache: yes
    name:
      - mosh
- name: allowlist mosh (60000-61000)
  become: yes
  ufw:
    rule: allow
    proto: udp
    port: '60000:61000'
