dependencies:
  - ufw
  - common
  - role: ansible-fail2ban
    become: yes
    fail2ban_banaction: ufw
    when: ansible_os_family == "Debian"
  - role: ansible-netdata
    become: yes
  - role: adriagalin.motd
    vars:
      ag_motd_remove_default_config: yes
      ag_motd_sysadmins_email: shepherdjerred@gmail.com
      ag_motd_sysadmins_signature: Jerred Shepherd
