- name: install applications
  become: yes
  package:
    update_cache: yes
    name:
      - shellcheck
      - exa
      - git
      - tree
      - vim
      - gnupg
      - zip
      - unzip
      - tmux
      - htop
      - curl
      - mosh
- name: Upgrade packages (apt)
  when: ansible_os_family == "Debian"
  apt: upgrade=dist
- name: Upgrade packages (yum)
  when: ansible_os_family == "CentOS" or ansible_distribution == "Amazon" and ansible_distribution_version == "2"
  yum: name=* state=latest
