---
- name: allowlist factorio (34197)
  become: yes
  ufw:
    rule: allow
    proto: udp
    port: '34197'
- name: allowlist factorio (27015)
  become: yes
  ufw:
    rule: allow
    proto: tcp
    port: '27015'
