- name: install docker
  become: yes
  package:
    name: docker
- name: add docker group
  become: yes
  group:
    name: docker
    state: present
- name: copy daemon config
  become: yes
  copy:
    src: "files/amongus/daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
- name: "add {{ target_user }} to docker group"
  become: yes
  user:
    name: "{{ target_user }}"
    groups:
      - docker
- name: enable docker service
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: docker
