---
- name: add repository key
  become: yes
  apt_key:
    url: http://linux-packages.resilio.com/resilio-sync/key.asc
- name: add repository
  become: yes
  apt_repository:
    repo: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
- name: install resilio-sync
  become: yes
  apt:
    name: resilio-sync
- name: copy config
  become: yes
  copy:
    src: files/nas/resilio-sync-config.json
    dest: /etc/resilio-sync/config.json
- name: enable resilio-sync service
  become: yes
  systemd:
    name: resilio-sync
    state: restarted
    enabled: yes
# https://help.resilio.com/hc/en-us/articles/204754759-What-ports-and-protocols-are-used-by-Sync-
- name: allowlist resilio sync listening port (52085)
  become: yes
  ufw:
    rule: allow
    port: '52085'
- name: allowlist resilio sync LAN discovery (multicast) (3838)
  become: yes
  ufw:
    rule: allow
    port: '3838'
