---
- name: install dependencies
  become: yes
  package:
    name: expect
- name: install gpg
  become: yes
  package:
    name: gpg
- name: create temp file
  tempfile:
    state:  file
    suffix: gpg
  register: temp_gpg
- name: copy gpg key to temp file
  copy:
    src: "Jerred Shepherd (9E0A6A73) â€“ Secret.asc"
    dest: "{{ temp_gpg.path }}"
- name: import gpg key
  shell: "gpg --pinentry-mode=loopback --passphrase {{ gpg_passphrase }} --import {{ temp_gpg.path }}"
  no_log: yes
- name: set gpg key trust
  shell: "expect -c \"spawn gpg --edit-key 9E0A6A73 trust quit; send \"5\ry\r\"; expect eof\""
