---
- name: install syncthing repository certificate
  become: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
- name: install syncthing repository
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
- name: install syncthing
  become: yes
  apt:
    update_cache: yes
    name:
      - syncthing
- name: create temp dir
  tempfile:
    state: directory
    suffix: syncthing
  register: tempdir
- name: clone syncthing github repo
  git:
    update: yes
    repo: https://github.com/syncthing/syncthing
    dest: "{{ tempdir.path }}"
    depth: 1
- name: copy syncthing systemd config
  become: yes
  copy:
    src: "{{ tempdir.path }}/syncthing/etc/linux-systemd/system/syncthing@.service"
    dest: "/etc/systemd/system/syncthing@{{ target_user }}.service"
    remote_src: yes
- name: enable syncthing service
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: "syncthing@{{ target_user }}.service"
- name: open port for syncthing
  become: yes
  ufw:
    rule: allow
    name: syncthing
