name: Ansible Deploy

on: [push]

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          options: |
            -e@group_vars/all/vault.yml
            --limit hades,nas
